# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Loïc Pinsard
tagline:          ''
description:      'My personal blog\nabout 3D Graphics, Game Designm, programming.'
url:              http://muream.github.io
baseurl:          /

author:
  name:           'Loïc Pinsard'
  url:            https://twitter.com/muream

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/muream/muream.github.io
